stages:
  - build_image
  - deploy_app

#build stage 
build:
  tags: docker-runner1
  stage: build_image
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t "$CI_REGISTRY_IMAGE":1.0 .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - main
deploy:
  stage: deploy_app
  tags: shell-runner1
  script:
    - docker pull "$CI_REGISTRY_IMAGE":1.0
    - docker run --restart always -d -p 81:80 --name netfoods-app "$CI_REGISTRY_IMAGE":1.0
  only:
    - main